### ISSUE TITLE
Don't use JSON for compliance specification format.

### ISSUE THREAD

**Issue by yyny** [toml-lang/compliance#9]
JSON is a simple, well defined and well supported data exchange format for representing hierarchical data like TOML files.
However, I have found several problems with using JSON for defining compliance specs:

 1. JSON is unordered.
 2. JSON is not `grep`-able/human-readable.
 3. JSON is not `diff`-able.
 4. Additional semantic rules need to be defined on top of JSON.

I will elaborate on each of these, and then propose an alternate format for defining compliance specs.

It is noteworthy to mention that these problems not only apply to the compliance specification file itself, but also to any encoder/decoder implementation tests that wish to comply to the format.

## 1. JSON is unordered

Many JSON encoders and decoders do not return table elements in the same order they were defined. This makes it impossible to test TOML encoders/decoders that want to keep insertion order stable without using a purpose-built JSON parser and maintaining the compliance spec to define the correct order. Still then, other tools for handling JSON data cannot be used, as they can also mess with this order, removing the major advantage of JSON. There is a way around this by defining table elements inside of arrays, although this still has all of the problems outlined below.

## 2. JSON is not `grep`-able/human-readable

Finding tests for specific TOML specs becomes harder when using the JSON format (Example: Finding specs testing dates/times where the first character is `0`). Additionally, JSON is not (designed to be) human-readable, making it harder to interpret the meaning of individual specs, which is harmful both for debugging failing tests, as well as for assuring the tests are TOML compliant.

## 3. JSON is not `diff`-able

It is a lot harder to give concise information about testing failures without this property. When using a line-based format, testing results can simply be compared to the compliance spec using the widely available `diff` tool.

## 4. Additional semantic rules need to be defined on top of JSON

The value types representable in TOML do not directly map to those representable in JSON. This means that a seperate format has to be defined just for representing TOML values in JSON. In the current implementation, this is done using a `{ "type": "<type>", "value": <value> }` object.

The type of a value is just one of many semantic rules defined by TOML. Some implementations might be interested in more information than what is currently provided. For example, some TOML encoders/decoders might be interested in the difference between `[normal]` and inline `{}` tables, complicating the spec verification process further.

In practice, a (small) semantic encoder/decoder has to always be written on top of any potential JSON implementation, and a specification for the semantic rule format has to be written, removing some of the advantages of using an established format in the first place.

## Conclusion

Any encoder/decoder wishing to test more advanced features of their TOML implementation have to not only write their own spec, but also their own runner, potentially using an incompatible format since the currently proposed JSON format is unnecessarily inconvenient to extend, wasting much of the collaborative effort of finding edge cases in encoders/decoders and defining them in a compliance spec file.

# Proposed Alternative Format

I propose using a new, purpose built format similar to [`gron`](https://github.com/TomNomNom/gron), where each value is presented on it's own line, as a `JavaScript`-like expression.

The goal of this format is to be easy for machines to parse, easy for humans to read and write, easy to grep, easy to diff (by sorting the lines), and easily extensible with new semantic rules (using the proposed comment syntax).

The proposed format is also relatively easy to convert to JSON, as to not require existing test implementations to be completely rewritten.

As a quick example, this TOML file:

```toml
best-day-ever = 1987-07-05T17:45:00Z

[number-theory]
boring = false
perfection = [6, 28, 496]
```

Would be written in a compliance spec as something like:

```py
best-day-ever = offset_datetime("1987-07-05T17:45:00Z")
number-theory = {}
number-theory.boring = boolean("false")
number-theory.perfection = [] # (inline)
number-theory.perfection[0] = integer("6")
number-theory.perfection[1] = integer("28")
number-theory.perfection[2] = integer("496")
```

As a more complete example, take the following TOML file from the [toml.io](https://toml.io/en) website:

<details>
<summary>TOML File</summary>

```toml
# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"
```
</details>

This could then be represented as:

<details>
<summary>Representation</summary>

```py
title = string("TOML Example")
owner = {}
owner.name = string("Tom Preston-Werner")
owner.dob = offset_datetime("1979-05-27T07:32:00-08:00")
database = {}
database.enabled = boolean("true")
database.ports = [] # (inline)
database.ports[0] = integer("8000")
database.ports[1] = integer("8001")
database.ports[2] = integer("8002")
database.data = [] # (inline)
database.data[0] = [] # (inline)
database.data[0][0] = string("delta")
database.data[0][1] = string("phi")
database.data[1] = [] # (inline)
database.data[1][0] = float("3.14")
database.temp_targets = {} # (inline)
database.temp_targets.cpu = float("79.5")
database.temp_targets.case = float("72.0")
servers = {}
servers.alpha = {}
servers.alpha.ip = string("10.0.0.1")
servers.alpha.role = string("frontend")
servers.beta = {}
servers.beta.ip = string("10.0.0.2")
servers.beta.role = string("backend")
```
</details>

And when sorted as:

<details>
<summary>Sorted Representation</summary>

```py
database = {}
database.data = [] # (inline)
database.data[0] = [] # (inline)
database.data[0][0] = string("delta")
database.data[0][1] = string("phi")
database.data[1] = [] # (inline)
database.data[1][0] = float("3.14")
database.enabled = true
database.ports = [] # (inline)
database.ports[0] = integer("8000")
database.ports[1] = integer("8001")
database.ports[2] = integer("8002")
database.temp_targets = {} # (inline)
database.temp_targets.case = float("72.0")
database.temp_targets.cpu = float("79.5")
owner = {}
owner.dob = offset_datetime("1979-05-27T07:32:00-08:00")
owner.name = string("Tom Preston-Werner")
servers = {}
servers.alpha = {}
servers.alpha.ip = string("10.0.0.1")
servers.alpha.role = string("frontend")
servers.beta = {}
servers.beta.ip = string("10.0.0.2")
servers.beta.role = string("backend")
title = string("TOML Example")
```
</details>

## Grammar

The grammar of the proposed syntax, in an "Extended [McKeeman Form](https://www.crockford.com/mckeeman.html)" where comments and simple regex patterns are allowed.

```emk
spec # A compliance spec contains one or more lines
    ""
    line \n spec

line # Every line contains a Key, it's expected Value, and an optional Comment.
    key space '=' space value comment?

key # A Key has JavaScript-like syntax, except that identifiers follow TOML rules.
    identifier ('.' keystring | '.' identifier | '[' digits ']')*

value # A Value has JavaScript-like syntax, except that identifiers follow TOML rules.
    "{}"
    "[]"
    identifier '(' string ')'

comment # The syntax for a comment.
    space* '#' [^\n]*

string # Every special character in a string MUST be escaped with it's hex escape. Non-ASCII characters are represented as hex escapes in UTF-8.
    '"' ( [^\x00-\x1f\x7f-\xff"] | "\x" x x ) '"'

keystring # To ease in grep-ing, key strings may also not contain any of `=.[]`
    '"' ( [^\x00-\x1f\x7f-\xff"=.\[\]] | "\x" x x ) '"'

# Aliases:

digits # Valid TOML integer.
    [0-9]
    [1-9] [0-9]*

x # Hex escapes MUST be lower-case.
    [0-9a-f]

idnchar # Valid TOML identifier character.
    [0-9A-Za-z_-]

identifier # Valid TOML identifier.
    idnchar+

space # A single space (Tab characters not allowed in compliance specs).
    ' '
```

## Semantics

The function-like syntax of `Value` should have a name matching one of those defined in [the current JSON encoding](https://github.com/toml-lang/compliance/blob/25c1a4e1354cac955d77f618d066af58962d2d2d/docs/json-encoding.md), except that spaces are replaced by underscores:

 - `string`
 - `integer`
 - `float`
 - `boolean`
 - `offset_datetime`
 - `local_datetime`
 - `local_date`
 - `local_time`
 - `array`

Comments should be ignored when comparing results, unless both results contain a comment. A line with no comment should compare equal to a line with an empty comment.
This allows testing of semantic differences between encoders/decoders that support this without hampering encoders/decoders that don't.

Proposed comments:
```
For inline tables/arrays:
# (inline)
# (not inline)
For recovering the original representation of a value (For example: "1e3" and "1000.0" should compare equal but have different representations):
# repr="<representation>"
For recovering the type of a string:
# type=single_quote
# type=double_quote
# type=triple_single_quote
# type=triple_double_quote
```

Proposed semantic comment syntax is to allow only recognize following types of comments:
```
# (boolean property)
# key="value" # a "String" as per the Extended McKeeman.
# key=enum_value
# <any of the above>, <any of the above>, ...
```

A well-defined semantic comment syntax would allow for multiple semantic properties to be defined on a single key-value pair.
I propose this simple, naive format, as to keep the overall format human-readable.

## Considerations

The above proposed format does not have complementing syntax-highlighting available. One consideration is to fully take the `gron` route, and make every single line a valid `Python/JavaScript` expression (Using the right comment syntax, using `[""]` for problematic keys, etc.), although this might also harm readability.

The comment syntax could be removed in favor of explicit properties, although the benefit of comments is that they are easily removed with regular expressions.

Semantic comments should potentially not contain any of `=.[]{}"#` as to ease with grepping.
Semantic string properties could then still be defined with a different type of quote and/or using hex escapes.

As none of the disadvantages of the JSON format outlined above apply to semantic comments, there is an argument to be made they should be formatted as JSON objects as to increase compatibility, although I personally prefer the proposed (human-readable) format.

**Comment by arp242** [comment]
The big advantage of JSON is that it's widely supported and well-understood.

People need to implement a parser for your custom format in order to test this. That's a lot of extra work, and also something that can potentially be buggy. It's super-confusing if your test tools have bugs; it's really the last place where you want to have bugs.

You need a bit of extra code to add the type hints; with the JSON approach from https://github.com/BurntSushi/toml-test adding and removing the JSON tags is 53 and 75 lines of very straightforward code, in Go (not the most concise language). Your grammar would be a lot more effort and code – you need to write a parser to test your other parser, and then you should probably also write a test for the parser that tests your parser to make sure it's correct.

To address some specific issues:

> JSON is unordered.

An `order` key can be added for this; or maybe it can be solved without it. Either way, this sounds like a solvable problem.

Although, I'm not sure if *every possible thing* needs to be tested by these kind of tests. There are many (potential) library-specific details (such as ordering), and you can just test that in the library's unit tests. The way I do this is loop over all the tests, test them one-by-one, and then have a map which runs additional tests for some tests.

Also, since TOML doesn't say anything about ordering different implementations can disagree on the order, so there isn't "one valid way" to do this. Should it be ordered in the order it appears in the file? Should it be ordered alphabetically? (and should "Martin" be sorted before "martin"? Should ḿ be sorted as `m`?)

> JSON is not grep-able/human-readable.

Certainly true, but it's "human-readable enough" for this purpose IMO, and I don't think either this or "grepability" are really priorities. This is a "write once, never look at it again" kind of affair. 

> JSON is not diff-able.

I think this is a solvable problem, and the errors that toml-test currently gives are actually pretty useful/decent. I spent a lot of time looking at various errors over the last weeks, and have never really been confused "what is even failing with this?!"

This is what you get now:

```
FAIL valid/key-dotted
     Values for key 'name.last' don't match:
       Expected:     Dent
       Your encoder: Dentt
```

Followed by more detailed on what exactly the input/output was. This doesn't seem too bad to me. I don't know what output this tool gives as I haven't worked on it, but in toml-test at least this is mostly a solved problem (and always has been).

Also, tests should really be small; toml-test contains a few large tests that should really be split up (e.g. [this](https://github.com/BurntSushi/toml-test/blob/master/tests/valid/key-dotted.toml)), which makes it easier to run just one of them, skip tests you haven't implemented (yet), so "diff" is of somewhat limited value in the first place.

> Additional semantic rules need to be defined on top of JSON.

Certainly not great, but better than thinking of an entire new very domain-specific language.

**Comment by eksortso** [comment]
Regarding ordering, and aside from general advice, TOML v1.0.0 only has this to say, which affirms @arp242 's comment.

>Key/value pairs within tables are not guaranteed to be in any specific order.

I've been thinking of suggesting a way to order related tables, which would be challenging to implement in JSON, but not impossible, given the right semantics.

**Comment by pradyunsg** [comment]
While I appreciate the amount of energy and thought you've likely invested in this, I think using a DSL/purpose built format is a no-go for this suite -- the requirement for testing a TOML decoder/encoder can not be "write another encoder/decoder for a DSL".

I've spent a lot of energy lately on walls-of-text on GitHub (and @arp242 has said things in a much more polite way than my draft post here). So, I'm gonna try to quickly summarize my thoughts in bullets instead:

- JSON objects being unordered isn't a problem, since TOML objects are also unordered.
- JSON is human-readable enough, `jq` is a thing and this test suite is still fairly "greppable". More importantly perhaps, it is also something that folks will be familiar with already.
- Honestly, even pretty-print-the-JSON-and-show-the-diff will be clear enough to most of the audience of this tool (there are folks writing language parsers after all). Both toml-test's runner and this repository's runner do a good-enough job on this front IMO. Plus, we can make improvements on this front without needing to change the underlying format.
- I disagree that "additional semantic rules over JSON" is somehow a problem here. It would be great if we had some "lower overhead" way to do so, but what we have here is certainly good-enough, especially given the write-once-and-forget approach we need to take here.

Overall, I do not think JSON is a bad format choice for this suite and using a DSL would not improve upon that.

I'm going to close this now to reflect that it's very unlikely that I can be convinced that using a DSL here is a good idea, but folks are welcome to discuss this further, if they want to.

**Comment by yyny** [comment]
> Regarding ordering, and aside from general advice, TOML v1.0.0 only has this to say, which affirms @arp242 's comment.
> 
> > Key/value pairs within tables are not guaranteed to be in any specific order.
> 
> I've been thinking of suggesting a way to order related tables, which would be challenging to implement in JSON, but not impossible, given the right semantics.

> JSON objects being unordered isn't a problem, since TOML objects are also unordered.

Regardless of what the TOML standard says, implementations _need_ to be able to check the ordering of elements. An implementation implementing inline editing (like `tomlkit` or the project I'm working on) would need to preserve the order of elements as originally specified in the document. Any other ordering (like alphabetical or some kind of hash) can be derived from the input.

> People need to implement a parser for your custom format in order to test this. That's a lot of extra work, and also something that can potentially be buggy. It's super-confusing if your test tools have bugs; it's really the last place where you want to have bugs.

People don't need to implement a parser for my format _at all_, that's the whole point of recommending it over JSON, using `sed`, `grep` and `diff` is enough for basic testing.

It's actually the other way around: for me to be able to test my own TOML implementation with the existing specs from `BurntSushi/toml-test`, I had to implement my own runner from scratch to parse the auxiliary information on top of JSON to be able to test all the corner-cases of my implementation, which I ended up giving up on because the format of those spec files is poorly specified and not designed to be extensible in the first place (example: `toml-test` has inconsistent element ordering and float/date encoding).
None of the current runners even allow for _any_ additional keys to be added to the JSON spec, since they compare the JSON objects literally.

It was less work for me to write my own runner and spec files then it would have been to fix all the JSON tests and the runner in `toml-test` (specifically w.r.t. the ordering of the table elements). My encoder/decoder can output a format that is much simpler to emit/parse than nested JSON, and my test runner is literally a one line shell script.

The current JSON format is fine for _just_ testing TOML compliance (by doing a value-by-value comparison of the JSON objects themselves as the runner does currently), but any more sophisticated tests will require actual parsing of the JSON structure, and at that point you're just defining another DSL. It seems much more productive to come up with a simple and extensive DSL from the start, rather than having each implementation implement their own test runners/test formats and tests on top of the compliance specs that all mostly test the same thing.

If anyone actually prefers reading/writing or emitting JSON (doubtful), it's trivial to write a converter that can convert between the DLS and JSON format.

**Comment by yyny** [comment]
On another note, if the use JSON is really decided on for whatever reason, as a compromise it is still possible to implement the beneficial features of the DSL into a JSON format as well:

```js
[
  { "key": ["person"], "value": { "type": "inline-table", "value": null }, /* Auxiliary JSON data ... */ },
  { "key": ["person", "name"], "value": { "type": "string", "value": "Jon Doe" }, /* ... */ },
  { "key": ["person", "age"], "value": { "type": "integer", "value": "24" }, /* ... */ },
]
```

**Comment by arp242** [comment]
Comments aren't valid in JSON; some JSON parsers can deal with it, but many don't and it's not part of the JSON specification.

> Regardless of what the TOML standard says, implementations need to be able to check the ordering of elements.

You already can; in pseudo-code:

```
order_checks = {
    'valid/test1': ['key1', 'key2'],
    ...
}

for test in list_tests()
    run_test(test)
    if order_checks[test]
        test_order()
    end
end
```

Or something along those lines.

This is how I test both the metadata and errors in the Go toml library, and it doesn't strike me as more work.

These tests should always pass for any valid TOML implementation. Like I said, there is no "correct" order so it's impossible to define this here. No matter what we end up using as a format, the order will not be a part of this.

> People don't need to implement a parser for my format at all, that's the whole point of recommending it over JSON, using sed, grep and diff is enough for basic testing.

That's a parser, albeit an ad-hoc one. And you need to encode it like this as well.

I've probably written more shell scripts than most, but it's not very portable, many people aren't very familiar with it (at literally every job I've had I had to fix up people's shell scripts), and you'll very likely run in to trouble with the tests that contain NULL bytes (you can't store null bytes in variables; you can work around that by never storing anything in a variable, but it's a huge caveat that will almost certainly cause a few people to become very confused why it's not working as they expect).

And personally I don't think diffs are especially better error than `key foo should be a string, but your encoder returned it as an integer`

> example: toml-test has inconsistent element ordering and float/date encoding).

What are the problems with the float and date encoding? This should just be fixed? I don't see how this related to JSON though.

The ordering of keys should now be consistent; although this changed recently (on the same day as you reported this issue). All tests are now run it through a little `jsonfmt` tool before saving which uses Go `json.MarshalIndent()` to format it, which among other things takes care of the order. The order may not be what you want though and you probably shouldn't rely on it.

> If anyone actually prefers reading/writing or emitting JSON (doubtful), it's trivial to write a converter that can convert between the DLS and JSON format.

Wouldn't it be easy to do it the other way round too then if that's what you prefer?
